import Head from "next/head";
import styles from "../styles/Home.module.css";
import web3Modal from "web3modal";
import { providers, Contract, BigNumber } from "ethers";
import { useState, useEffect, useRef } from "react";
import { ABI, address } from "../constants";

export default function Home() {
  const [walletConnected, setWalletConnected] = useState(false);
  const [joinedWhitelist, setJoinedWhitelist] = useState(false);
  const [loading, setLoading] = useState(false);
  const [numberWhitelisted, setNumberWhitelisted] = useState(0);
  const web3ModalRef = useRef();

  const providerOrSigner = async (needSigner = false) => {
    const provider = await web3ModalRef.current.connect();
    const web3Provider = new providers.Web3Provider(provider);

    const { chainId } = await web3Provider.getNetwork();

    if (chainId !== 5) {
      window.alert("Change the network to Goerli");
      throw new Error("Change network to Goerli");
    }

    if (needSigner) {
      const signer = web3Provider.getSigner();
      return signer;
    }
    return web3Provider;
  };

  const addAddressToWhitelist = async () => {
    try {
      const signer = await providerOrSigner(true);
      const whitelistContract = new Contract(address, ABI, signer);
      console.log(whitelistContract);
      const tx = await whitelistContract.addAddressToWhitelist();
      setLoading(true);
      await tx.wait();
      setLoading(false);
      await getNumberOfWhitelistedAddress();
      setJoinedWhitelist(true);
    } catch (error) {
      console.log(error);
    }
  };

  const getNumberOfWhitelistedAddress = async () => {
    try {
      const provider = await providerOrSigner(true);
      const whitelistContract = new Contract(address, ABI, provider);
      console.log(whitelistContract);

      const _numberOfWhitelistedAddress =
        await whitelistContract.numAddressesWhitelisted();
      console.log(_numberOfWhitelistedAddress);
      setNumberWhitelisted(_numberOfWhitelistedAddress.toNumber());
    } catch (error) {
      console.log(error);
    }
  };

  const checkIfAddressIsInWhitelist = async () => {
    try {
      const provider = await providerOrSigner(true);
      const whitelistContract = new Contract(address, ABI, provider);

      const userAddress = provider.getAddress();
      const _joinedWaitlist = await whitelistContract.whitelistedAddresses(
        userAddress
      );
      console.log(_joinedWaitlist);
      setJoinedWhitelist(_joinedWaitlist);
    } catch (error) {
      console.log(error);
    }
  };

  const connectWallet = async () => {
    try {
      await providerOrSigner();
      setWalletConnected(true);
      checkIfAddressIsInWhitelist();
      getNumberOfWhitelistedAddress();
    } catch (error) {
      console.log(error);
    }
  };

  const renderButton = () => {
    if (walletConnected) {
      if (joinedWhitelist) {
        return (
          <div className={styles.description}>
            Thanks for joining the Whitelist!
          </div>
        );
      } else if (loading) {
        return <button className={styles.button}>Loading...</button>;
      } else {
        return (
          <button onClick={addAddressToWhitelist} className={styles.button}>
            Join the Whitelist
          </button>
        );
      }
    } else {
      return (
        <button onClick={connectWallet} className={styles.button}>
          Connect your wallet
        </button>
      );
    }
  };

  useEffect(() => {
    if (!walletConnected) {
      web3ModalRef.current = new web3Modal({
        network: "goerli",
        providerOptions: {},
        disableInjectedProvider: false,
      });
    }
  }, [walletConnected]);

  useEffect(() => {
    getNumberOfWhitelistedAddress()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Whitelist DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div>
          <h1 className={styles.title}>Welcome to Crypto Devs!</h1>
          <div className={styles.description}>
            Its an NFT collection for developers in Crypto.
          </div>
          <div className={styles.description}>
            {numberWhitelisted} have already joined the Whitelist
          </div>
          {renderButton()}
        </div>
        <div>
          <img className={styles.image} src="./crypto-devs.svg" />
        </div>
      </div>

      <footer className={styles.footer}>
        Made with &#10084; by Crypto Devs
      </footer>
    </div>
  );
}
